### ISSUE TITLE
 Missing  xxxx.dll

### ISSUE THREAD

**Issue by stonedreamforest** [maldevel/driver-loader#1]
Missing VCRUNTIME140.dll
 Missing MSVCP140.dll

**Comment by maldevel** [comment]
Microsoft Visual C++ 2015 Redistributable - https://www.microsoft.com/en-us/download/details.aspx?id=52685

**Comment by stonedreamforest** [comment]
i already install it(x64)  ，Missing xxx.dll yet

**Comment by maldevel** [comment]
The prebuilt executable in releases is x86 and under Windows 10 using vc++ 2015 x86 seems to work. Did you try to build a x64 version from source code?

**Comment by maldevel** [comment]
I will build a x64 version and upload it to releases.

**Comment by maldevel** [comment]
https://github.com/maldevel/driver-loader/releases/tag/v1.0-x64

**Comment by stonedreamforest** [comment]
normal work
:+1:
